class_name PrimeInventory extends Resource

@export var state := {
	"Charge Beam" : 0,
	"Power Beam" : 0,
	"Wave Beam" : 0,
	"Ice Beam" : 0,
	"Plasma Beam" : 0,
	"Missile Launcher" : 0,
	"Grapple Beam" : 0,
	"Combat Visor" : 0,
	"Scan Visor" : 0,
	"Thermal Visor" : 0,
	"X-Ray Visor" : 0,
	"Space Jump Boots" : 0,
	"Energy Tank" : 0,
	"Morph Ball" : 0,
	"Morph Ball Bomb" : 0,
	"Boost Ball" : 0,
	"Spider Ball" : 0,
	"Power Bomb" : 0,
	"Power Suit" : 0,
	"Varia Suit" : 0,
	"Gravity Suit" : 0,
	"Phazon Suit" : 0,
	"Super Missile" : 0,
	"Wavebuster" : 0,
	"Ice Spreader" : 0,
	"Flamethrower" : 0,
	
	"Missile Expansion" : 0,
	"Power Bomb Expansion" : 0,
}
